/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mbientlab.warble;

public class Library {
    public static String version() {
        return Gatt.LIB_WARBLE.warble_lib_version();
    }

    public static String config() {
        return Gatt.LIB_WARBLE.warble_lib_config();
    }
}
