/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mbientlab.warble;

import jnr.ffi.LibraryLoader;

public class Library {
    static final Native WARBLE = LibraryLoader.create(Native.class).load("warble");

    public static String version() {
        return WARBLE.warble_lib_version();
    }

    public static String config() {
        return WARBLE.warble_lib_config();
    }
}
